### PR TITLE
Allow the setting of context properties in queries

### PR DESCRIPTION
**Pull request by mruwnik**
At http://druid.io/docs/latest/Querying.html there is a 'Query Context' object specified which describes how druid should execute the query. This can be used e.g. to set a timeout for a given query

### CODE REVIEW

**Comment by dganguli** [comment]
@fjy @xvrl  looks good to me!

**Comment by fjy** [comment]
@mruwnik Do you mind signing our CLA: http://druid.io/community/cla.html

**Comment by mruwnik** [comment]
done

**Comment by fjy** [comment]
Thanks for the contrib!!

**Pull request merged**
