### PR TITLE
Fix a few bugs introduced by the Python 3 support and add test coverage

### PR DESCRIPTION
**Pull request by griffy**
This adds pytest as the testing tool and adds a `test` command that can be invoked with: `python setup.py test`

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by drcrallen** [comment]
@griffy Went through some PRs that were in the backlog, can you please fix conflicts?

**Comment by griffy** [comment]
@drcrallen @fjy Fixed the conflicts.

**Comment by xvrl** [comment]
@griffy do you mind squashing commits, and I'll merge

**Comment by griffy** [comment]
@xvrl Squashed

**Pull request merged**
