### PR TITLE
make simplejson optional, except on python < 2.6

### PR DESCRIPTION
**Pull request by graphaelli**

### CODE REVIEW

**Comment by dganguli** [comment]
Thanks! LGTM. @xvrl @fjy please merge.

**Comment by drcrallen** [comment]
@graphaelli : I jumped the gun a little here Do you mind signing the CLA at http://druid.io/community/cla.html

**Comment by graphaelli** [comment]
signed

**Comment by drcrallen** [comment]
@graphaelli Thanks a ton!

**Pull request merged**
