### PR TITLE
add missing sys import

### PR DESCRIPTION
**Pull request by graphaelli**
used on https://github.com/metamx/pydruid/blob/310dd7057be8d5cc1af9c54a508ebfa060161a09/pydruid/client.py#L125

### CODE REVIEW

**Comment by griffy** [comment]
I just put up a PR (https://github.com/metamx/pydruid/pull/21) that addresses this and a few other bugs I introduced when adding Python 3 support if you'd like to review it

**Comment by graphaelli** [comment]
Great, I'll close this if that gets merged first.  I'll try to get a review in too.

**Comment by xvrl** [comment]
@graphaelli @drcrallen is this still needed, now that #21 has been merged?

**Comment by xvrl** [comment]
@graphaelli after merging #21, client.py already imports sys, so I think we can safely close this.

**Comment by raphaellig** [comment]
thanks!

**Pull request closed without merging**
